package com.android.projectnew.DataController.ArrayData;

public class ArrayProvKota {

    public String[] provinsi = {"Pilih",
            "Aceh","Bali","Banten","Bengkulu","DI Yogyakarta","DKI Jakarta","Gorontalo",
            "Jambi","Jawa Barat","Jawa Tengah","Jawa Timur","Kalimantan Barat","Kalimantan Selatan",
            "Kalimantan Tengah","Kalimantan Timur","Kalimantan Utara","Kepulauan Bangka Belitung",
            "Kepulauan Riau","Lampung","Maluku","Maluku Utara","Nusa Tenggara Barat","Nusa Tenggara Timur",
            "Papua","Papua Barat","Riau","Sulawesi Barat","Sulawesi Selatan","Sulawesi Tengah",
            "Sulawesi Tenggara","Sulawesi Utara","Sumatera Barat","Sumatera Selatan","Sumatera Utara"
    };

    public final String Pilih[] = {"Pilih!"};
    public final String Aceh[] = {"Kabupaten Aceh Barat Daya","Kabupaten Aceh Barat","Kabupaten Aceh Besar","Kabupaten Aceh Jaya","Kabupaten Aceh Selatan","Kabupaten Aceh Singkil","Kabupaten Aceh Tamiang","Kabupaten Aceh Tengah","Kabupaten Aceh Tenggara","Kabupaten Aceh Timur","Kabupaten Aceh Utara","Kabupaten Bener Meriah","Kabupaten Bireuen","Kabupaten Gayo Lues","Kabupaten Nagan Raya","Kabupaten Pidie Jaya","Kabupaten Pidie","Kabupaten Simeulue","Kota Banda Aceh","Kota Langsa","Kota Lhokseumawe","Kota Sabang","Kota Subulussalam"};
    public final String Bali[] = {"Kabupaten Badung","Kabupaten Bangli","Kabupaten Buleleng","Kabupaten Gianyar","Kabupaten Jembrana","Kabupaten Karangasem","Kabupaten Klungkung","Kabupaten Tabanan","Kota Denpasar"};
    public final String Banten[] = {"Kabupaten Lebak","Kabupaten Pandeglang","Kabupaten Serang","Kabupaten Tangerang","Kota Cilegon","Kota Serang","Kota Tangerang Selatan","Kota Tangerang"};
    public final String Bengkulu[] = {"Kabupaten Bengkulu Selatan","Kabupaten Bengkulu Tengah","Kabupaten Bengkulu Utara","Kabupaten Kaur","Kabupaten Kepahiang","Kabupaten Lebong","Kabupaten Muko Muko","Kabupaten Rejang Lebong","Kabupaten Seluma","Kota Bengkulu"};
    public final String Yogyakarta[] = {"Kabupaten Bantul","Kabupaten Gunung Kidul","Kabupaten Kulon Progo","Kabupaten Sleman","Kota Yogyakarta"};
    public final String DKI_Jakarta[] = {"Kabupaten Kepulauan Seribu","Kota Jakarta Barat","Kota Jakarta Pusat","Kota Jakarta Selatan","Kota Jakarta Timur","Kota Jakarta Utara"};
    public final String Gorontalo[] = {"Kabupaten Boalemo","Kabupaten Bone Bolango","Kabupaten Gorontalo Utara","Kabupaten Gorontalo","Kabupaten Pohuwato","Kota Gorontalo"};
    public final String Jambi[] = {"Kabupaten Batang Hari","Kabupaten Bungo","Kabupaten Kerinci","Kabupaten Merangin","Kabupaten Muaro Jambi","Kabupaten Sarolangun","Kabupaten Tanjung Jabung Barat","Kabupaten Tanjung Jabung Timur","Kabupaten Tebo","Kota Jambi","Kota Sungaipenuh"};
    public final String Jawa_Barat[] = {"Kabupaten Bandung Barat","Kabupaten Bandung","Kabupaten Bekasi","Kabupaten Bogor","Kabupaten Ciamis","Kabupaten Cianjur","Kabupaten Cirebon","Kabupaten Garut","Kabupaten Indramayu","Kabupaten Karawang","Kabupaten Kuningan","Kabupaten Majalengka","Kabupaten Pangandaran","Kabupaten Purwakarta","Kabupaten Subang","Kabupaten Sukabumi","Kabupaten Sumedang","Kabupaten Tasikmalaya","Kota Bandung","Kota Banjar","Kota Bekasi","Kota Bogor","Kota Cimahi"};
    public final String Jawa_Tengah[] = {"Kabupaten Banjarnegara","Kabupaten Banyumas","Kabupaten Batang","Kabupaten Blora","Kabupaten Boyolali","Kabupaten Brebes","Kabupaten Cilacap","Kabupaten Demak","Kabupaten Grobogan","Kabupaten Jepara","Kabupaten Karanganyar","Kabupaten Kebumen","Kabupaten Kendal","Kabupaten Klaten","Kabupaten Kudus","Kabupaten Magelang","Kabupaten Pati","Kabupaten Pekalongan","Kabupaten Pemalang","Kabupaten Purbalingga","Kabupaten Purworejo","Kabupaten Rembang","Kabupaten Semarang"};
    public final String Jawa_Timur[] = {"Kabupaten Bangkalan","Kabupaten Banyuwangi","Kabupaten Blitar","Kabupaten Bojonegoro","Kabupaten Bondowoso","Kabupaten Gresik","Kabupaten Jember","Kabupaten Jombang","Kabupaten Kediri","Kabupaten Lamongan","Kabupaten Lumajang","Kabupaten Madiun","Kabupaten Magetan","Kabupaten Malang","Kabupaten Mojokerto","Kabupaten Nganjuk","Kabupaten Ngawi","Kabupaten Pacitan","Kabupaten Pamekasan","Kabupaten Pasuruan","Kabupaten Ponorogo","Kabupaten Probolinggo","Kabupaten Sampang","Kabupaten Sidoarjo","Kota Surabaya"};
    public final String Kal_Bar[] = {"Kabupaten Bengkayang","Kabupaten Kapuas Hulu","Kabupaten Kayong Utara","Kabupaten Ketapang","Kabupaten Kubu Raya","Kabupaten Landak","Kabupaten Melawi","Kabupaten Mempawah","Kabupaten Sambas","Kabupaten Sanggau","Kabupaten Sekadau","Kabupaten Sintang","Kota Pontianak","Kota Singkawang"};
    public final String Kal_Sel[] = {"Kabupaten Balangan","Kabupaten Banjar","Kabupaten Barito Kuala","Kabupaten Hulu Sungai Selatan","Kabupaten Hulu Sungai Tengah","Kabupaten Hulu Sungai Utara","Kabupaten Kotabaru","Kabupaten Tabalong","Kabupaten Tanah Bumbu","Kabupaten Tanah Laut","Kabupaten Tapin","Kota Banjarbaru","Kota Banjarmasin"};
    public final String Kal_Teng[] = {"Kabupaten Barito Selatan","Kabupaten Barito Timur","Kabupaten Barito Utara","Kabupaten Gunung Mas","Kabupaten Kapuas","Kabupaten Katingan","Kabupaten Kotawaringin Barat","Kabupaten Kotawaringin Timur","Kabupaten Lamandau","Kabupaten Murung Raya","Kabupaten Pulang Pisau","Kabupaten Seruyan","Kabupaten Sukamara","Kota Palangka Raya",};
    public final String Kal_Tim[] = {"Kabupaten Berau","Kabupaten Kutai Barat","Kabupaten Kutai Kartanegara","Kabupaten Kutai Timur","Kabupaten Mahakam Ulu","Kabupaten Paser","Kabupaten Penajam Paser Utara","Kota Balikpapan","Kota Bontang","Kota Samarinda"};
    public final String Kal_Utr[] = {"Kabupaten Bulungan","Kabupaten Malinau","Kabupaten Nunukan","Kabupaten Tana Tidung","Kota Tarakan"};
    public final String Kep_Belitung[] = {"Kabupaten Bangka Barat","Kabupaten Bangka Selatan","Kabupaten Bangka Tengah","Kabupaten Bangka","Kabupaten Belitung Timur","Kabupaten Belitung","Kota Pangkal Pinang"};
    public final String Kep_Riau[] = {"Kabupaten Bintan","Kabupaten Karimun","Kabupaten Kepulauan Anambas","Kabupaten Lingga","Kabupaten Natuna","Kota Batam","Kota Tanjung Pinang"};
    public final String Lampung[] = {"Kabupaten Lampung Barat","Kabupaten Lampung Selatan","Kabupaten Lampung Tengah","Kabupaten Lampung Timur","Kabupaten Lampung Utara","Kabupaten Mesuji","Kabupaten Pesawaran","Kabupaten Pesisir Barat","Kabupaten Pringsewu","Kabupaten Tanggamus","Kabupaten Tulang Bawang Barat","Kabupaten Tulang Bawang","Kabupaten Way Kanan","Kota Bandar Lampung","Kota Metro"};
    public final String Maluku[] = {"Kabupaten Buru Selatan","Kabupaten Buru","Kabupaten Kepulauan Aru","Kabupaten Maluku Barat Daya","Kabupaten Maluku Tengah","Kabupaten Maluku Tenggara Barat","Kabupaten Maluku Tenggara","Kabupaten Seram Bagian Barat","Kabupaten Seram Bagian Timur","Kota Ambon","Kota Tual"};
    public final String Maluku_Utr[] = {"Kabupaten Halmahera Barat","Kabupaten Halmahera Selatan","Kabupaten Halmahera Tengah","Kabupaten Halmahera Timur","Kabupaten Halmahera Utara","Kabupaten Kepulauan Sula","Kabupaten Pulau Morotai","Kabupaten Pulau Taliabu","Kota Ternate","Kota Tidore Kepulauan"};
    public final String Ntb[] = {"Kabupaten Bima","Kabupaten Dompu","Kabupaten Lombok Barat","Kabupaten Lombok Tengah","Kabupaten Lombok Timur","Kabupaten Lombok Utara","Kabupaten Sumbawa Barat","Kabupaten Sumbawa","Kota Bima","Kota Mataram"};
    public final String Ntt[] = {"Kabupaten Alor","Kabupaten Belu","Kabupaten Ende","Kabupaten Flores Timur","Kabupaten Kupang","Kabupaten Lembata","Kabupaten Malaka","Kabupaten Manggarai Barat","Kabupaten Manggarai Timur","Kabupaten Manggarai","Kabupaten Nagekeo","Kabupaten Ngada","Kabupaten Rote Ndao","Kabupaten Sabu Raijua","Kabupaten Sikka","Kabupaten Sumba Barat Daya","Kabupaten Sumba Barat","Kabupaten Sumba Tengah","Kabupaten Sumba Timur","Kabupaten Timor Tengah Selatan","Kabupaten Timor Tengah Utara","Kota Kupang"};
    public final String Papua[] = {"Kabupaten Asmat","Kabupaten Biak Numfor","Kabupaten Boven Digoel","Kabupaten Deiyai","Kabupaten Dogiyai","Kabupaten Intan Jaya","Kabupaten Jayapura","Kabupaten Jayawijaya","Kabupaten Keerom","Kabupaten Kepulauan Yapen","Kabupaten Lanny Jaya","Kabupaten Mamberamo Raya","Kabupaten Mamberamo Tengah","Kabupaten Mappi","Kabupaten Merauke","Kabupaten Mimika","Kabupaten Nabire","Kabupaten Nduga","Kabupaten Paniai","Kabupaten Pegunungan Bintang","Kabupaten Puncak Jaya","Kabupaten Puncak","Kabupaten Sarmi"};
    public final String Papua_Bar[] = {"Kabupaten Fakfak","Kabupaten Kaimana","Kabupaten Manokwari Selatan","Kabupaten Manokwari","Kabupaten Maybrat","Kabupaten Pegunungan Arfak","Kabupaten Raja Ampat","Kabupaten Sorong Selatan","Kabupaten Sorong","Kabupaten Tambrauw","Kabupaten Teluk Bintuni","Kabupaten Teluk Wondama","Kota Sorong"};
    public final String Riau[] = {"Kabupaten Bengkalis","Kabupaten Indragiri Hilir","Kabupaten Indragiri Hulu","Kabupaten Kampar","Kabupaten Kepulauan Meranti","Kabupaten Kuantan Singingi","Kabupaten Pelalawan","Kabupaten Rokan Hilir","Kabupaten Rokan Hulu","Kabupaten Siak","Kota Dumai","Kota Pekanbaru"};
    public final String Sul_Bar[] = {"Kabupaten Majene","Kabupaten Mamasa","Kabupaten Mamuju Tengah","Kabupaten Mamuju Utara","Kabupaten Mamuju","Kabupaten Polewali Mandar"};
    public final String Sul_Sel[] = {"Kabupaten Bantaeng","Kabupaten Barru","Kabupaten Bone","Kabupaten Bulukumba","Kabupaten Enrekang","Kabupaten Gowa","Kabupaten Jeneponto","Kabupaten Kepulauan Selayar","Kabupaten Luwu Timur","Kabupaten Luwu Utara","Kabupaten Luwu","Kabupaten Maros","Kabupaten Pangkajene Kepulauan","Kabupaten Pinrang","Kabupaten Sidenreng Rappang","Kabupaten Sinjai","Kabupaten Soppeng","Kabupaten Takalar","Kabupaten Tana Toraja","Kabupaten Toraja Utara","Kabupaten Wajo","Kota Makassar","Kota Palopo"};
    public final String Sul_Teng[] = {"Kabupaten Banggai Kepulauan","Kabupaten Banggai Laut","Kabupaten Banggai","Kabupaten Buol","Kabupaten Donggala","Kabupaten Morowali Utara","Kabupaten Morowali","Kabupaten Parigi Moutong","Kabupaten Poso","Kabupaten Sigi","Kabupaten Tojo Una-Una","Kabupaten Toli-Toli","Kota Palu"};
    public final String Sul_Tgr[] = {"Kabupaten Bombana","Kabupaten Buton Selatan","Kabupaten Buton Tengah","Kabupaten Buton Utara","Kabupaten Buton","Kabupaten Kolaka Timur","Kabupaten Kolaka Utara","Kabupaten Kolaka","Kabupaten Konawe Kepulauan","Kabupaten Konawe Selatan","Kabupaten Konawe Utara","Kabupaten Konawe","Kabupaten Muna Barat","Kabupaten Muna","Kabupaten Wakatobi","Kota Bau-Bau","Kota Kendari"};
    public final String Sul_Utr[] = {"Kabupaten Bolaang Mongondow Selatan","Kabupaten Bolaang Mongondow Timur","Kabupaten Bolaang Mongondow Utara","Kabupaten Bolaang Mongondow","Kabupaten Kepulauan Sangihe","Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)","Kabupaten Kepulauan Talaud","Kabupaten Minahasa Selatan","Kabupaten Minahasa Tenggara","Kabupaten Minahasa Utara","Kabupaten Minahasa","Kota Bitung","Kota Kotamobagu","Kota Manado","Kota Tomohon"};
    public final String Sum_Bar[] = {"Kabupaten Agam","Kabupaten Dharmasraya","Kabupaten Kepulauan Mentawai","Kabupaten Lima Puluh Kota","Kabupaten Padang Pariaman","Kabupaten Pasaman Barat","Kabupaten Pasaman","Kabupaten Pesisir Selatan","Kabupaten Sijunjung","Kabupaten Solok Selatan","Kabupaten Solok","Kabupaten Tanah Datar","Kota Bukittinggi","Kota Padang Panjang","Kota Padang","Kota Pariaman","Kota Payakumbuh","Kota Sawah Lunto","Kota Solok"};
    public final String Sum_Sel[] = {"Kabupaten Banyuasin","Kabupaten Empat Lawang","Kabupaten Lahat","Kabupaten Muara Enim","Kabupaten Musi Banyuasin","Kabupaten Musi Rawas Utara","Kabupaten Musi Rawas","Kabupaten Ogan Ilir","Kabupaten Ogan Komering Ilir","Kabupaten Ogan Komering Ulu Selatan","Kabupaten Ogan Komering Ulu Timur","Kabupaten Ogan Komering Ulu","Kabupaten Penukal Abab Lematang Ilir","Kota Lubuk Linggau","Kota Pagar Alam","Kota Palembang","Kota Prabumulih"};
    public final String Sum_Utr[] = {"Kabupaten Asahan","Kabupaten Batu Bara","Kabupaten Dairi","Kabupaten Deli Serdang","Kabupaten Humbang Hasundutan","Kabupaten Karo","Kabupaten Labuhanbatu Selatan","Kabupaten Labuhanbatu Utara","Kabupaten Labuhanbatu","Kabupaten Langkat","Kabupaten Mandailing Natal","Kabupaten Nias Barat","Kabupaten Nias Selatan","Kabupaten Nias Utara","Kabupaten Nias","Kabupaten Padang Lawas Utara","Kabupaten Padang Lawas","Kabupaten Pakpak Bharat","Kabupaten Samosir","Kabupaten Serdang Bedagai","Kabupaten Simalungun","Kabupaten Tapanuli Selatan","Kabupaten Tapanuli Tengah"};

}
